# Generated by Django 3.2 on 2021-04-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                ("user_name", models.CharField(max_length=60)),
                ("password", models.CharField(max_length=60)),
                ("accesslevel", models.CharField(max_length=60)),
                ("unit", models.CharField(max_length=60)),
                ("position", models.CharField(max_length=60)),
                ("activity", models.CharField(max_length=60)),
                ("pointe", models.CharField(max_length=60)),
                ("creator", models.CharField(max_length=60)),
                ("Updating", models.CharField(max_length=60)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
            ],
        ),
    ]
