# Generated by Django 3.2 on 2021-05-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiB", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="Updating",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="members",
            name="accesslevel",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="members",
            name="activity",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="members",
            name="creator",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="members",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="members",
            name="first_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="members",
            name="last_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="members",
            name="password",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="members",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="members",
            name="pointe",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="members",
            name="position",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="members",
            name="unit",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="members",
            name="user_name",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
