# Generated by Django 3.2 on 2021-05-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiB", "0002_auto_20210501_1338"),
    ]

    operations = [
        migrations.RenameField(
            model_name="members",
            old_name="first_name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="members",
            old_name="last_name",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="members",
            old_name="user_name",
            new_name="user_name",
        ),
    ]
