# Generated by Django 3.2 on 2021-05-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiB', '0003_auto_20210501_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='accesslevel',
            field=models.CharField(choices=[('EM', 'Employee'), ('AD', 'Administrator')], max_length=2),
        ),
        migrations.AlterField(
            model_name='members',
            name='position',
            field=models.CharField(max_length=60),
        ),
    ]
