# Generated by Django 3.2 on 2021-05-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiB', '0004_auto_20210501_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='members',
            name='position',
        ),
        migrations.AddField(
            model_name='members',
            name='department',
            field=models.CharField(blank=True, choices=[('CE', 'Central'), ('SO', 'South')], max_length=2),
        ),
        migrations.AlterField(
            model_name='members',
            name='accesslevel',
            field=models.CharField(blank=True, choices=[('EM', 'Employee'), ('AD', 'Administrator')], max_length=2),
        ),
        migrations.AlterField(
            model_name='members',
            name='unit',
            field=models.CharField(blank=True, choices=[('MA', 'Management'), ('SE', 'Services')], max_length=2),
        ),
    ]
