# Generated by Django 3.2 on 2021-05-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiB', '0005_auto_20210501_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='accesslevel',
            field=models.CharField(blank=True, choices=[('EMPLOYEE', 'Employee'), ('ADMINISTRATOR', 'Administrator')], max_length=60),
        ),
        migrations.AlterField(
            model_name='members',
            name='department',
            field=models.CharField(blank=True, choices=[('CENTRAL', 'Central'), ('SOUTH', 'South')], max_length=60),
        ),
        migrations.AlterField(
            model_name='members',
            name='unit',
            field=models.CharField(blank=True, choices=[('MANAGEMENT', 'Management'), ('SERVICES', 'Services')], max_length=60),
        ),
    ]
