# Generated by Django 3.2 on 2021-05-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiB', '0006_auto_20210502_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='activity',
            field=models.CharField(blank=True, choices=[('Employee', 'Disabled'), ('Active', 'Active')], max_length=60),
        ),
        migrations.AddField(
            model_name='members',
            name='position',
            field=models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Boss', 'Boss')], max_length=60),
        ),
        migrations.AlterField(
            model_name='members',
            name='unit',
            field=models.CharField(blank=True, choices=[('Management', 'Management'), ('Services', 'Services')], max_length=60),
        ),
    ]
