# Generated by Django 3.2 on 2021-05-02 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiB', '0007_auto_20210502_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='members',
            name='Updating',
            field=models.CharField(default=models.CharField(blank=True, max_length=60), max_length=120),
        ),
        migrations.AlterField(
            model_name='members',
            name='creator',
            field=models.CharField(default=models.CharField(blank=True, max_length=60), max_length=120),
        ),
    ]
