# Generated by Django 3.2 on 2021-05-02 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiB', '0008_auto_20210502_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Updating',
            field=models.CharField(default=datetime.datetime.now, max_length=120),
        ),
        migrations.AlterField(
            model_name='members',
            name='creator',
            field=models.CharField(default=datetime.datetime.now, max_length=120),
        ),
    ]
