# Generated by Django 3.2 on 2021-05-02 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiB', '0010_auto_20210502_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Updating',
            field=models.CharField(blank=True, default=models.CharField(blank=True, max_length=60), max_length=120),
        ),
        migrations.AlterField(
            model_name='members',
            name='creator',
            field=models.CharField(blank=True, default={'', datetime.datetime.now, models.CharField(blank=True, max_length=60)}, max_length=120),
        ),
    ]
