# Generated by Django 3.2 on 2021-05-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiB', '0013_auto_20210502_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Updating',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='members',
            name='creator',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
