# Generated by Django 3.2 on 2021-05-02 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiB', '0014_auto_20210502_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='creator',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='members',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
