# Generated by Django 3.2 on 2021-05-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiB', '0016_alter_members_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='password',
            field=models.TextField(max_length=60),
        ),
    ]
