# Generated by Django 3.2 on 2021-05-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiB', '0017_alter_members_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='password',
            field=models.CharField(max_length=60),
        ),
    ]
