# Generated by Django 3.2 on 2021-05-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiB', '0018_alter_members_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Updating',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='members',
            name='accesslevel',
            field=models.CharField(blank=True, choices=[('EMPLOYEE', 'Employee'), ('ADMINISTRATOR', 'Administrator')], max_length=600),
        ),
        migrations.AlterField(
            model_name='members',
            name='activity',
            field=models.CharField(blank=True, choices=[('Employee', 'Disabled'), ('Active', 'Active')], max_length=600),
        ),
        migrations.AlterField(
            model_name='members',
            name='creator',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='members',
            name='department',
            field=models.CharField(blank=True, choices=[('CENTRAL', 'Central'), ('SOUTH', 'South')], max_length=600),
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(blank=True, max_length=2540),
        ),
        migrations.AlterField(
            model_name='members',
            name='first_name',
            field=models.CharField(blank=True, max_length=6000),
        ),
        migrations.AlterField(
            model_name='members',
            name='last_name',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='members',
            name='password',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='members',
            name='phone',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='members',
            name='pointe',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='members',
            name='position',
            field=models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Boss', 'Boss')], max_length=600),
        ),
        migrations.AlterField(
            model_name='members',
            name='unit',
            field=models.CharField(blank=True, choices=[('Management', 'Management'), ('Services', 'Services')], max_length=600),
        ),
        migrations.AlterField(
            model_name='members',
            name='user_name',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
