# Generated by Django 3.2 on 2021-05-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiB', '0019_auto_20210502_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminstor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=6000)),
                ('ADM_ID', models.ManyToManyField(to='apiB.Members')),
            ],
        ),
    ]
