# Generated by Django 3.2 on 2021-05-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiB', '0024_alter_members_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='profile',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
