# Generated by Django 3.2 on 2021-05-05 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiB', '0027_alter_members_pointe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6000)),
                ('ADM_ID_ForeignKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiB.members')),
            ],
        ),
    ]
